name: Deploy To EC2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: echo "${{ secrets.ENV }}" > .env
      - run: npm run build

  Deploy:
    runs-on: ubuntu-latest
    needs: Check
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: 깃헙 레포지토리 불러오기
        uses: actions/checkout@v4
      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: 의존성 설치
        run: npm ci
      - name: .env 파일 생성
        run: |
          echo "${{ secrets.ENV }}" > .env
      - name: 빌드파일 압축하기
        run: tar -czvf project.tar.gz dist package.json package-lock.json
      - name: scp 사용하여 EC2에 빌드파일 전송하기
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.tar.gz
          target: /home/ec2-user/6th-Moving-4Team-BE
      - name: SSH로 EC2에 접속해서 Express 서버 배포하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: ENV
          script_stop: true
          script: |
            cd /home/ec2-user/6th-Moving-4Team-BE 
            tar -xvf project.tar.gz
            rm -rf project.tar.gz
            echo "$ENV" > .env
            npm ci
            npm run build
            pm2 start dist/server.js --name app || pm2 restart app
